word = input().lower()
word = word.replace("a","")
word = word.replace("e","")
word = word.replace("i","")
word = word.replace("o","")
word = word.replace("u","")
word = word.replace("y","")
result = "".join(f".{word[i]}" for i in range(len(word)))
print(result)